### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by Gujal00** [Twilight0/plugin.video.streamlink-tester#1]
Can you please add some usage examples to Readme.md?
such as plugin://plugin.video.streamlink-tester?type=BLAH&url=BLAH etc
Also how to add any additional headers such as cookies, referer, user-agent etc.

Thanks

**Comment by Twilight0** [comment]
Hi there. Yes, good idea, I will provide with the next version, which will also allow plugin options.

**Comment by Gujal00** [comment]
Thanks for the examples
